### PR TITLE
nav-barAdded

### PR DESCRIPTION
**Pull request by robinathon**
### Fixes #<number>
<Do not delete this template>
Description: <provide a description> The title should be short and relevant.

#### Checklist
- [ ] I've followed the Contributing guidelines provided in the repository.
- [ ] I've made the changes which were demanded in the linked issue.
- [ ] I've tested my code on a Chromium based browser.
- [ ] I've tested my code on Mozilla Firefox.
- [ ] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

### CODE REVIEW

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
Decrease the height of the navbar. It looks too thick. Change the font styles to be consistent with the design.

**Review by EmperorYP7 — COMMENTED** [review]
@robinathon You've done a great job. However, I find the work done in #19 to be more in line with the design. So, I am dropping this PR.

**Comment by tusharjain0022** [comment]
As the issue was assigned to Utkarsh so we need to consider his PR first. If he's unable to make the requested changes then we can go ahead with this one.

**Review by SrijanSriv — COMMENTED** [review]
This is a nice piece of code. However I would prefer if sass or anything not discussed was not added to it (not that's sass a big deal). I prefer the mui structure by @utkarsh0908 but good to know that if that pr is not updated then we have something really nice.

**Pull request closed without merging**
