### PR TITLE
Added Docs

### PR DESCRIPTION
**Pull request by anish853**

### CODE REVIEW

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
Committing to the `main` branch is not a good practice. For this to work correctly, you need to branch from `dev` branch and create a PR from that branch to `houseofgeeks:dev`. This ensures that the `houseofgeeks:main` branch won't have any merge conflicts.

**Comment by EmperorYP7** [comment]
@anish853 Kindly refer to this doc: https://github.com/houseofgeeks/tap/blob/dev/CONTRIBUTING.md

**Comment by SrijanSriv** [comment]
LGTM! :rocket: 
Solved some conflicts. @EmperorYP7 might wanna review his change request if initiated.

**Review by EmperorYP7 — APPROVED** [review]
LGTM

**Pull request merged**
