### PR TITLE
added navbar

### PR DESCRIPTION
**Pull request by utkarsh0908**
### Fixes #<number>
<Do not delete this template>
Description: <provide a description> Added navbar and a drawer for smaller devices. Need some work on responsiveness.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

### CODE REVIEW

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
Screenshot 2022-01-04 at 8 49 54 PM

Increase the top padding and decrease the right padding of every word in the navbar.

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
Increase the height of the navbar. It looks too narrow. Make sure to center the text vertically after doing so.

**Comment by SrijanSriv** [comment]
LGTM. The footer has to fixed a bit accordingly with more mui-based designs, but that's an issue for later.

**Comment by SrijanSriv** [comment]
@all-contributors add @utkarsh0908 for Code

**Pull request merged**
